#!/usr/bin/env bash
# script  displays the content of the file /etc/passwd
# and username, user id, Home directory path for the user
while read -r line
do
    echo "$line" | cut -d: -f1,3,6
done < "/etc/passwd"
