#!/usr/bin/env bash
# This script is displaying 4 bad luck, 8 is your chance
i=1
while ((i<=10))
do
    if ((i==4))
    then
	echo "bad luck"
    elif((i==8))
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((i++))
done
