#!/usr/bin/env bash
# displays numbers from 1 to 20
# 4 and then bad luck from China for the 4th loop iteration
# 9 and then bad luck from Japan for the 9th loop iteration
# 17 and then bad luck from Italy for the 17th loop iteration
i=1
while ((i <= 20))
do
    echo $i
    case $i in
	4)
	    echo 'bad luck from China'
	    ;;
	9)
	    echo 'bad luck from Japan'
	    ;;
	17)
	    echo 'bad luck from Italy'
	    ;;
    esac
    ((i++))
done
